name: CI

on:
  push:

jobs:
  mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift -version
      - name: Build and Test
        run: swift test

  linux:
    strategy:
      fail-fast: false
      matrix:
        swift_version: ['5.1', '5.2', '5.3']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v1
      - run: swift test --enable-test-discovery
