name: CI

on:
  push:

jobs:
  mac:
    strategy:
      matrix:
        xcode_version: ['11', '11.1', '11.2']
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift -version
      - name: Build and Test
        run: swift test
  linux:
    strategy:
      matrix:
        swift_version: ['5.0', '5.1']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v1
      - run: swift test
